---
title: "Sparks Foundation Project"
format: html
editor: visual
---

SampleSuperstore

```{r}
library(ggplot2)
library(nycflights13)
library(dplyr)
library(tidyverse)
library(openintro)
library(tidyverse)
library(scales)
library(plotly)
library(patchwork)
library(gghighlight)
library(ggiraph) 
library(ISLR2)
library(janitor)
library(gapminder)
library(palmerpenguins)
library(forcats)

```

```{r}
#SampleSuperstore<-read.csv("SampleSuperstore.csv",header=TRUE,sep=",")
#SampleSuperstore<-SampleSuperstore|>drop_na()
#SampleSuperstore
```

```{r}

# Specify the URL of the dataset
url <- "https://drive.usercontent.google.com/u/0/uc?id=1lV7is1B566UQPYzzY8R2ZmOritTW299S&export=download"

# Download the dataset using the read.csv function
# and specify the delimiter used in the dataset (e.g. ',' or ';')
SampleSuperstore <- read.csv(url, header=TRUE,sep=",")
SampleSuperstore
```

```{r}
#Sales by Sub-Category

# Select and rename columns
SubCategory_data1 <- SampleSuperstore %>%
  dplyr::select(Sales,Sub.Category)#%>%
 # rename(SubCategory = Sub.Category)

# Group by and summarise
#sscs-sale by by sub category summary
#TSSC-total sale by sub category
SSCS <- SubCategory_data1 %>%
  group_by(Sub.Category) %>%
  summarise(TSSC = sum(Sales, na.rm = TRUE)) %>%
  arrange(desc(TSSC))

#Reorder the SubCategory factor
SSCS$Sub.Category <- fct_reorder(SSCS$Sub.Category, SSCS$TSSC, .desc = TRUE)

# Plot using ggplot
p1<-ggplot(SSCS, aes(x = Sub.Category, y = TSSC,data_id =Sub.Category)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Sales by Sub-Category",
       x = "Sub-Category",
       y = "Sales") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = .75))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p1,width_svg = 10, height_svg = 6)


#From the above analysis, we can see that the "Fasteners" sub-category has the lowest sales. This could be a potential area to focus on to increase sales.
```

```{r}
#Profit by Sub-Category

# Select and rename columns
SubCategory_data2 <- SampleSuperstore %>%
  dplyr::select(Profit, Sub.Category) %>%
  rename(SubCategory = Sub.Category)

# Group by and summarise
#PSCS- profit by by sub category summary
#TPSC-total profit by sub category
PSCS<- SubCategory_data2 %>%
  group_by(SubCategory) %>%
  summarise(TPSC = sum(Profit, na.rm = TRUE)) %>%
  arrange(desc(TPSC))

#Reorder the SubCategory factor
PSCS$SubCategory <- fct_reorder(PSCS$SubCategory, PSCS$TPSC, .desc = TRUE)

# Plot using ggplot
p2<-ggplot(PSCS, aes(x = SubCategory, y = TPSC,data_id =SubCategory)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Profit By SubCategory",
       x = "Sub-Category",
       y = "Profit") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p2,width_svg = 10, height_svg = 6)

#From the above analysis, we can see that the "Tables,Bookcases and Supplies" sub-category has the lowest profit. This could be a potential area to focus on to increase profitability.
```

```{r}
#Sales by Region:

# Select and rename columns
region_data1 <- SampleSuperstore %>%
  dplyr::select(Sales,Region)

# Group by and summarise
#SRS-sale by region summary
#TSR-total sale by region
SRS <- region_data1 %>%
  group_by(Region) %>%
  summarise(TSR = sum(Sales, na.rm = TRUE)) %>%
    arrange(desc(TSR))

#Reorder the SubCategory factor
SRS$Region <- fct_reorder(SRS$Region,SRS$TSR, .desc = TRUE)

# Plot using ggplot
p3<-ggplot(SRS, aes(x = Region, y = TSR,data_id =Region)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Sales by Region",
       x = "Region",
       y = "Sales") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p3,width_svg = 10, height_svg = 6)

#From the above analysis, we can see that the "Southern" region has the lowest sales. This could be a potential area to focus on to increase sales.
```

```{r}
#Profit by Region:

# Select and rename columns
region_data2 <- SampleSuperstore %>%
  dplyr::select(Profit,Region)

# Group by and summarise
#PRS-sale by region summary
#TPR-total profit by region
PRS <- region_data2 %>%
  group_by(Region) %>%
  summarise(TPR = sum(Profit, na.rm = TRUE)) %>%
    arrange(desc(TPR))

#Reorder the SubCategory factor
PRS$Region <- fct_reorder(PRS$Region,PRS$TPR, .desc = TRUE)

# Plot using ggplot
p4<-ggplot(PRS, aes(x = Region, y = TPR,data_id=Region)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Profit By Region",
       x = "Region",
       y = "Profit") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p4,width_svg = 10, height_svg = 6)

#From the above analysis, we can see that the "Central" region has the lowest profit. This could be a potential area to focus on to increase profitability.
```

```{r}
#Sale by Segment:

# Select and rename columns
segment_data1 <- SampleSuperstore %>%
  dplyr::select(Segment,Sales)

# Group by and summarise
#SSS-sale by segment summary
#TSS-total sale by segment
SSS <- segment_data1%>%
  group_by(Segment) %>%
  summarise(TSS = sum(Sales, na.rm = TRUE)) %>%
    arrange(desc(TSS))

#Reorder the SubCategory factor
SSS$Segment <- fct_reorder(SSS$Segment, SSS$TSS, .desc = TRUE)

# Plot using ggplot
p5<-ggplot(SSS, aes(x = Segment, y = TSS,data_id=Segment)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Sales By Segment",
       x = "Segment",
       y = "Sales") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p5,width_svg = 10, height_svg = 6)

#From the above analysis, we can see that the "Home Office Segment" has the lowest sales. This could be a potential area to focus on to increase profitability.
```

```{r}
#Profit by Segment:

# Select and rename columns
segment_data2 <- SampleSuperstore %>%
  dplyr::select(Segment,Profit)

# Group by and summarise
#PSS-profit by segment summary
#TPS-total profit by segmwent
PSS <- profit_data %>%
  group_by(Segment) %>%
  summarise(TPS = sum(Profit, na.rm = TRUE)) %>%
    arrange(desc(TPS))

#Reorder the SubCategory factor
PSS$Segment <- fct_reorder(PSS$Segment, PSS$TPS, .desc = TRUE)

# Plot using ggplot
p6<-ggplot(PSS, aes(x = Segment, y = TPS,data_id=Segment)) +
  geom_bar_interactive(stat = "identity") +
  labs(title = "Total Profit By Segment",
       x = "Segment",
       y = "Profit") +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE, big.mark = ",")) +
  scale_y_continuous(labels = label_dollar())+
  theme_dark() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  theme(
        axis.text=element_text(size=15),
        axis.title=element_text(size=25),
        plot.title=element_text(size=40)
        )

girafe(ggobj=p6,width_svg = 10, height_svg = 6)

#From the above analysis, we can see that the "Home Office Segment" has the lowest profit. This could be a potential area to focus on to increase profitability.
```

```{r}
#Discount and Profit Correlation
#Discount and Sales Correlation
mod <- lm(Profit ~ Discount, data = SampleSuperstore)
mod
ggplot(data=SampleSuperstore, aes(Profit,Discount)) +
  geom_point() +
  # Add a regression line
  geom_smooth(method = "lm", se = TRUE, color = "blue")+
  labs(title = " Profit and Discount Correlation")

ggplot(data=SampleSuperstore, aes(Sales,Discount)) +
  geom_point() +
  # Add a regression line
  geom_smooth(method = "lm", se = TRUE, color = "red")+
  labs(title = " Sales and Discount  Correlation")

#This suggests that discounting may not be an effective strategy for increasing profits,but it may however increase sales which can create market power for the brand.

#Different Segment react almost the different way to discount offered,with consumer segment making most purchases as the discount increases.
```
